# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ckan_url: str=None, username: str=None):  # noqa: E501
        """RequestBody - a model defined in Swagger

        :param ckan_url: The ckan_url of this RequestBody.  # noqa: E501
        :type ckan_url: str
        :param username: The username of this RequestBody.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'ckan_url': str,
            'username': str
        }

        self.attribute_map = {
            'ckan_url': 'ckan_url',
            'username': 'username'
        }
        self._ckan_url = ckan_url
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'RequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestBody of this RequestBody.  # noqa: E501
        :rtype: RequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ckan_url(self) -> str:
        """Gets the ckan_url of this RequestBody.

        ログイン対象のCKANのURL  # noqa: E501

        :return: The ckan_url of this RequestBody.
        :rtype: str
        """
        return self._ckan_url

    @ckan_url.setter
    def ckan_url(self, ckan_url: str):
        """Sets the ckan_url of this RequestBody.

        ログイン対象のCKANのURL  # noqa: E501

        :param ckan_url: The ckan_url of this RequestBody.
        :type ckan_url: str
        """
        if ckan_url is None:
            raise ValueError("Invalid value for `ckan_url`, must not be `None`")  # noqa: E501

        self._ckan_url = ckan_url

    @property
    def username(self) -> str:
        """Gets the username of this RequestBody.

        CKANのログインに使用するCKANのユーザ名  # noqa: E501

        :return: The username of this RequestBody.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RequestBody.

        CKANのログインに使用するCKANのユーザ名  # noqa: E501

        :param username: The username of this RequestBody.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username
