# 設定ファイル

# gRPC通信
[gRPC]
ML_PORT = [::]:50251

# 分析モデル
[ANALYSIS]
CLF_MODEL_THEME = ./model/model_theme.pkl
CLF_MODEL_KEYWORDS = ./model/model_keywords.pkl
MLB_MODEL_KEYWORDS = ./model/multilabelbinarizer_keywords.pkl

# データディレクトリ
[DIR_RECIEVE]
DIR_RECIEVE = ./data/recieve_file

