# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyse_data.proto

from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='analyse_data.proto',
    package='analysis',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b('\n\x12\x61nalyse_data.proto\x12\x08\x61nalysis\"J\n\x0eRequestMessage\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x61nalyse_type\x18\x03 \x01(\t\"N\n\x0cReplyMessage\x12\x14\n\x0c\x62\x65st_analyse\x18\x01 \x01(\t\x12\x13\n\x0btop_analyse\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\t2Y\n\x0e\x41nalyseService\x12G\n\rAnalyseServer\x12\x18.analysis.RequestMessage\x1a\x16.analysis.ReplyMessage\"\x00(\x01\x30\x01\x62\x06proto3')
)


_REQUESTMESSAGE = _descriptor.Descriptor(
    name='RequestMessage',
    full_name='analysis.RequestMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='title', full_name='analysis.RequestMessage.title', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='description', full_name='analysis.RequestMessage.description', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='analyse_type', full_name='analysis.RequestMessage.analyse_type', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=32,
    serialized_end=106,
)


_REPLYMESSAGE = _descriptor.Descriptor(
    name='ReplyMessage',
    full_name='analysis.ReplyMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='best_analyse', full_name='analysis.ReplyMessage.best_analyse', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='top_analyse', full_name='analysis.ReplyMessage.top_analyse', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='probability', full_name='analysis.ReplyMessage.probability', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=108,
    serialized_end=186,
)

DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ReplyMessage'] = _REPLYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), {
    'DESCRIPTOR': _REQUESTMESSAGE,
    '__module__': 'analyse_data_pb2'
    # @@protoc_insertion_point(class_scope:analysis.RequestMessage)
})
_sym_db.RegisterMessage(RequestMessage)

ReplyMessage = _reflection.GeneratedProtocolMessageType('ReplyMessage', (_message.Message,), {
    'DESCRIPTOR': _REPLYMESSAGE,
    '__module__': 'analyse_data_pb2'
    # @@protoc_insertion_point(class_scope:analysis.ReplyMessage)
})
_sym_db.RegisterMessage(ReplyMessage)


_ANALYSESERVICE = _descriptor.ServiceDescriptor(
    name='AnalyseService',
    full_name='analysis.AnalyseService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=188,
    serialized_end=277,
    methods=[
        _descriptor.MethodDescriptor(
            name='AnalyseServer',
            full_name='analysis.AnalyseService.AnalyseServer',
            index=0,
            containing_service=None,
            input_type=_REQUESTMESSAGE,
            output_type=_REPLYMESSAGE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_ANALYSESERVICE)

DESCRIPTOR.services_by_name['AnalyseService'] = _ANALYSESERVICE

# @@protoc_insertion_point(module_scope)
