# -*- coding: utf-8 -*-
import json

MESSAGE_MAP = {
    # CADDE認証エラー
    'releaseckan_CKANAPIError'								: 'ユーザ情報取得時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'create_dummy_auth_code_Exception'						: 'ダミー認可コード生成にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',
    'create_keycloak_redirect_uri_Exception'				: 'keycloak画面リダイレクトURI作成時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',
    'post_token_authorization_code_ConfigError'				: 'トークン取得(認可コード)におけるコンフィグ情報が不正です。\n管理者に問い合わせてください。',
    'post_token_authorization_code_AuthServerError'			: 'トークン取得(認可コード)時に認証サーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'post_token_authorization_code_GetTokenError'			: 'トークン取得(認可コード)時にトークン取得に失敗しました。\n管理者に問い合わせてください。',
    'post_token_introspect_ConfigError'						: 'トークン検証におけるコンフィグ情報が不正です。\n管理者に問い合わせてください。',
    'post_token_introspect_NotMatchCode'					: 'トークン検証時にリフレッシュトークン取得エラーが発生しました。\n管理者に問い合わせてください。',
    'post_token_introspect_AuthServerError'					: 'トークン検証時に認証サーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'post_token_introspect_IntrospectError'					: 'トークン検証時にトークン検証に失敗しました。\n管理者に問い合わせてください。',
    'post_token_refresh_ConfigError'						: 'トークン更新におけるコンフィグ情報が不正です。\n管理者に問い合わせてください。',
    'post_token_refresh_NotMatchCode'						: 'トークン更新時にリフレッシュトークン取得エラーが発生しました。\n管理者に問い合わせてください。',
    'post_token_refresh_AuthServerError'					: 'トークン更新時に認証サーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'post_token_refresh_TokenRefreshError'					: 'トークン更新時にトークン更新に失敗しました。\n管理者に問い合わせてください。',
    'logout_keycloak_Exception'								: 'keycloakログアウト時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',
    'logout_keycloak_NotMatchCode'							: 'keycloakログアウト時にリフレッシュトークン取得エラーが発生しました。\n管理者に問い合わせてください。',
    'logout_keycloak_KeycloakError'							: 'keycloakログアウト時にkeycloakでエラーが発生しました。\n管理者に問い合わせてください。',
    'logout_keycloak_KeycloakLogoutError'					: 'keycloakログアウト時にログアウトに失敗しました。\n管理者に問い合わせてください。',

    # PostgreSQLエラー
    'get_cadde_user_id_postgres_SQLAlchemyError'			: 'DBアクセスに失敗しました。\n管理者に問い合わせてください。',
    'get_cadde_user_id_postgres_Exception'					: 'DBアクセスで例外が発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_info_postgres_NotFound'					: '未登録ユーザです。\n管理者に問い合わせてください。',
    'get_ckan_user_info_postgres_SQLAlchemyError'			: 'DBアクセスに失敗しました。\n管理者に問い合わせてください。',
    'get_ckan_user_info_postgres_Exception'					: 'DBアクセスで例外が発生しました。\n管理者に問い合わせてください。',
    'add_new_record_postgres_IntegrityError'				: '登録済みのCADDEユーザIDです。登録済みのCADDEユーザIDと同じCADDEユーザIDは設定できません。',
    'add_new_record_postgres_SQLAlchemyError'				: 'DBアクセスに失敗しました。\n管理者に問い合わせてください。',
    'add_new_record_postgres_Exception'						: 'DBアクセスで例外が発生しました。\n管理者に問い合わせてください。',
    'update_record_postgres_IntegrityError'					: '登録済みのCADDEユーザIDです。登録済みのCADDEユーザIDと同じCADDEユーザIDは設定できません。',
    'update_record_postgres_SQLAlchemyError'				: 'DBアクセスに失敗しました。\n管理者に問い合わせてください。',
    'update_record_postgres_Exception'						: 'DBアクセスで例外が発生しました。\n管理者に問い合わせてください。',
    'update_password_postgres_SQLAlchemyError'				: 'DBアクセスに失敗しました。\n管理者に問い合わせてください。',
    'update_password_postgres_Exception'					: 'DBアクセスで例外が発生しました。\n管理者に問い合わせてください。',

    # CKAN認証エラー
    'authenticate_ckan_user_ConfigError'				: '認証拡張機能実行時におけるコンフィグ情報が不正です。\n管理者に問い合わせてください。',
    'authenticate_ckan_user_release_AuthServerError'			: '横断検索用CKANの認証拡張機能実行時に認証拡張コンテナでエラーが発生しました。\n管理者に問い合わせてください。',
    'authenticate_ckan_user_release_RequestError'		: '横断検索用CKANの認証拡張機能実行時にリクエストエラーが発生しました。\n管理者に問い合わせてください。',
    'authenticate_ckan_user_release_AuthSeverException'			: '横断検索用CKANの認証拡張機能実行時に認証拡張コンテナで例外が発生しました。\n管理者に問い合わせてください。',
    'authenticate_ckan_user_detail_AuthServerError'             : '詳細検索用CKANの認証拡張機能実行時に認証拡張コンテナでエラーが発生しました。\n管理者に問い合わせてください。',
    'authenticate_ckan_user_detail_RequestError'		: '詳細検索用CKANの認証拡張機能実行時にリクエストエラーが発生しました。\n管理者に問い合わせてください。',
    'authenticate_ckan_user_detail_AuthSeverException'		: '詳細検索用CKANの認証拡張機能実行時に認証拡張コンテナで例外が発生しました。\n管理者に問い合わせてください。',
    # ログイン/ログアウトエラー
    'login_NotMatchUUID'									: 'カタログ作成ツールで発行したUUIDとkeycloakから取得したUUIDが一致しませんでした。\n管理者に問い合わせてください。',
    'login_Exception'										: 'ログイン時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',
    'logout_Exception'										: 'ログアウト時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # ユーザ取得エラー
    'get_ckan_user_release_NotAuthorized'					: 'ユーザ情報取得時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_NotFound'						: 'ユーザ情報取得時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_ValidationError'					: 'ユーザ情報取得時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_CKANAPIError'					: 'ユーザ情報取得時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_ServerIncompatibleError'			: 'ユーザ情報取得時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_AttributeError'					: 'ユーザ情報取得時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_Exception'						: 'ユーザ情報取得時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_release_DisableUser'						: '指定されたユーザは無効です。\n管理者に問い合わせてください。',
    'get_ckan_user_release_PasswordNotSame'					: '指定されたユーザではCKANにログインできませんでした。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_NotAuthorized'					: 'ユーザ情報取得時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_NotFound'							: 'ユーザ情報取得時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_ValidationError'					: 'ユーザ情報取得時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_CKANAPIError'						: 'ユーザ情報取得時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_ServerIncompatibleError'			: 'ユーザ情報取得時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_AttributeError'					: 'ユーザ情報取得時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_Exception'						: 'ユーザ情報取得時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_detail_DisableUser'						: '指定されたユーザは無効です。\n管理者に問い合わせてください。',
    'get_ckan_user_release_PasswordNotSame'					: '指定されたユーザではCKANにログインできませんでした。\n管理者に問い合わせてください。',
    'get_ckan_user_both_UserNotSame'						: '横断検索用CKANと詳細検索用CKANでユーザ情報が異なっています。\n管理者に問い合わせてください。',
    'get_ckan_user_config_ckan_NotFound'					: 'カタログ作成ツールのコンフィグのコンフィグ情報が不正です。\n管理者に問い合わせてください。',
    'users_Exception'										: 'ユーザ情報取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # ユーザ一覧取得エラー
    'fetch_ckan_userlist_release_NotAuthorized'				: 'ユーザ一覧取得時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_release_NotFound'					: 'ユーザ一覧取得時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_release_ValidationError'			: 'ユーザ一覧取得時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_release_CKANAPIError'				: 'ユーザ一覧取得横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_release_ServerIncompatibleError'	: 'ユーザ一覧取得時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_release_AttributeError'			: 'ユーザ一覧取得時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_release_Exception'					: 'ユーザ一覧取得時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_NotAuthorized'				: 'ユーザ一覧取得時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_NotFound'					: 'ユーザ一覧取得時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_ValidationError'			: 'ユーザ一覧取得時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_CKANAPIError'				: 'ユーザ一覧取得詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_ServerIncompatibleError'	: 'ユーザ一覧取得時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_AttributeError'				: 'ユーザ一覧取得時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'fetch_ckan_userlist_detail_Exception'					: 'ユーザ一覧取得時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'fetch_userlist_Exception'								: 'ユーザ一覧取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # ユーザ作成エラー
    'create_user_NoUsername'								: 'ユーザ名が未設定です。',
    'create_user_NoPassword'								: 'CKANユーザパスワードが未設定です。',
    'create_user_NoCaddeUserId'								: 'CADDEユーザIDが未設定です。',
    'create_user_NoEmail'									: 'メールアドレスが未設定です。',
    'create_user_NoOrganization'							: '組織名が未設定です。',
    'create_user_NoCkan'									: '登録先カタログサイトの設定が不正です。',
    'create_ckan_user_release_AlreadyExist'					: '既存のユーザです。\n既存のユーザ名と同じユーザ名は設定できません。',
    'create_ckan_user_detail_AlreadyExist'					: '既存のユーザです。\n既存のユーザ名と同じユーザ名は設定できません。',
    'create_ckan_user_release_NotAuthorized'				: 'ユーザ作成時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_release_NotFound'						: 'ユーザ作成時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_release_DuplicateDeletedUser'			: '削除済みのユーザです。\n一度作成したユーザ名と同じユーザ名は設定できません。',
    'create_ckan_user_release_DumlicateEmailAddressForward'	: '登録済みのメールアドレスです。\n登録済みのメールアドレスと同じメールアドレスは設定できません。',
    'create_ckan_user_release_ValidationError'				: 'ユーザ作成時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_release_CKANAPIError'					: 'ユーザ作成時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_release_ServerIncompatibleError'		: 'ユーザ作成時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_release_AttributeError'				: 'ユーザ作成時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_release_Exception'					: 'ユーザ作成時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_NotAuthorized'					: 'ユーザ作成時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_NotFound'						: 'ユーザ作成時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_DuplicateDeletedUser'			: '削除済みのユーザです。一度作成したユーザ名と同じユーザ名は設定できません。',
    'create_ckan_user_detail_DumlicateEmailAddressForward'	: '登録済みのメールアドレスです。登録済みのメールアドレスと同じメールアドレスは設定できません。',
    'create_ckan_user_detail_ValidationError'				: 'ユーザ作成時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_CKANAPIError'					: 'ユーザ作成時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_ServerIncompatibleError'		: 'ユーザ作成時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_AttributeError'				: 'ユーザ作成時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'create_ckan_user_detail_Exception'						: 'ユーザ作成時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'create_user_Exception'									: 'ユーザ作成時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # ユーザ更新エラー
    'update_user_NoUsername'								: 'ユーザ名が未設定です。',
    'update_user_NoPassword'								: 'CKANユーザパスワードが未設定です。',
    'update_user_NoCaddeUserId'								: 'CADDEユーザIDが未設定です。',
    'update_user_NoEmail'									: 'メールアドレスが未設定です。',
    'update_user_NoOrganization'							: '組織名が未設定です。',
    'update_user_NoCkan'									: '登録先カタログサイトの設定が不正です。',
    'update_user_NoReleaseCkanUrl'							: '外部横断検索カタログサイトURLが未設定です。',
    'update_user_NoReleaseCkanApikey'						: '外部横断検索カタログサイトAPIキーが未設定です。',
    'update_user_NoReleaseCkanUsername'						: '外部横断検索カタログサイトユーザ名が未設定です。',
    'update_user_NoDetailCkanUrl'							: '外部詳細検索カタログサイトURLが未設定です。',
    'update_user_NoDetailCkanApikey'						: '外部詳細検索カタログサイトAPIキーが未設定です。',
    'update_user_NodDtailCkanUsername'						: '外部詳細検索カタログサイトユーザ名が未設定です。',
    'update_ckan_user_release_NotAuthorized'				: 'ユーザ更新時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_release_NotFound'						: 'ユーザ更新時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_release_ValidationError'				: 'ユーザ更新時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_release_CKANAPIError'					: 'ユーザ更新時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_release_ServerIncompatibleError'		: 'ユーザ更新時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_release_AttributeError'				: 'ユーザ更新時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_release_Exception'					: 'ユーザ更新時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_NotAuthorized'					: 'ユーザ更新時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_NotFound'						: 'ユーザ更新時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_ValidationError'				: 'ユーザ更新時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_CKANAPIError'					: 'ユーザ更新時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_ServerIncompatibleError'		: 'ユーザ更新時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_AttributeError'				: 'ユーザ更新時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_detail_Exception'						: 'ユーザ更新時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',

    # ユーザパスワード更新エラー
    'update_user_password_NoUsername'										: 'ユーザ名が未設定です。再度やり直してください。',
    'update_user_password_NoOldPassword'									: '旧パスワードが未設定です。再度やり直してください。',
    'update_user_password_NoNewPassword'									: '新パスワードが未設定です。再度やり直してください。',
    'update_user_password_NoEmail'											: 'メールアドレスが未設定です。再度やり直してください。',
    'update_ckan_user_password_usershow_release_NotAuthorized'				: 'ユーザパスワード更新時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_release_NotFound'					: 'ユーザパスワード更新時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_release_ValidationError'			: 'ユーザパスワード更新時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_release_CKANAPIError'				: 'ユーザパスワード更新時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_release_ServerIncompatibleError'	: 'ユーザパスワード更新時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_release_AttributeError'				: 'ユーザパスワード更新時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_release_Exception'					: 'ユーザパスワード更新時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_NotAuthorized'				: 'ユーザパスワード更新時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_NotFound'					: 'ユーザパスワード更新時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_ValidationError'				: 'ユーザパスワード更新時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_CKANAPIError'				: 'ユーザパスワード更新時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_ServerIncompatibleError'		: 'ユーザパスワード更新時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_AttributeError'				: 'ユーザパスワード更新時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_usershow_detail_Exception'					: 'ユーザパスワード更新時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_MismatchPassword'							: '現在設定されているパスワードと一致しませんでした。',
    'update_ckan_user_password_userupdate_release_NotAuthorized'			: 'ユーザパスワード更新時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_release_NotFound'					: 'ユーザパスワード更新時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_release_ValidationError'			: 'ユーザパスワード更新時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_release_CKANAPIError'				: 'ユーザパスワード更新時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_release_ServerIncompatibleError'	: 'ユーザパスワード更新時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_release_AttributeError'			: 'ユーザパスワード更新時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_release_Exception'				: 'ユーザパスワード更新時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_NotAuthorized'				: 'ユーザパスワード更新時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_NotFound'					: 'ユーザパスワード更新時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_ValidationError'			: 'ユーザパスワード更新時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_CKANAPIError'				: 'ユーザパスワード更新時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_ServerIncompatibleError'	: 'ユーザパスワード更新時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_AttributeError'			: 'ユーザパスワード更新時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'update_ckan_user_password_userupdate_detail_Exception'					: 'ユーザパスワード更新時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'update_user_password_Exception'										: 'ユーザパスワード更新時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # ユーザ削除エラー
    'delete_ckan_user_release_NotAuthorized'				: 'ユーザ削除時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_release_ValidationError'				: 'ユーザ削除時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_release_CKANAPIError'					: 'ユーザ削除時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_release_ServerIncompatibleError'		: 'ユーザ削除時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_release_AttributeError'				: 'ユーザ削除時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_release_Exception'					: 'ユーザ削除時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_detail_NotAuthorized'					: 'ユーザ削除時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_detail_ValidationError'				: 'ユーザ削除時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_detail_CKANAPIError'					: 'ユーザ削除時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_detail_ServerIncompatibleError'		: 'ユーザ削除時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_detail_AttributeError'				: 'ユーザ削除時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'delete_ckan_user_detail_Exception'						: 'ユーザ削除時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'delete_postgres_SQLAlchemyError'						: 'DBアクセスに失敗しました。\n管理者に問い合わせてください。',
    'delete_postgres_Exception'								: 'DBアクセスで例外が発生しました。\n管理者に問い合わせてください。',
    'delete_user_Exception'									: 'ユーザ削除時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # カタログサイト情報取得エラー
    'get_ckan_info_release_NotAuthorized'					: 'カタログサイト情報取得時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_release_NotFound'						: 'カタログサイト情報取得時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_release_ValidationError'					: 'カタログサイト情報取得時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_release_CKANAPIError'					: 'カタログサイト情報取得時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_release_ServerIncompatibleError'			: 'カタログサイト情報取得時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_release_AttributeError'					: 'カタログサイト情報取得時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_release_Exception'						: 'カタログサイト情報取得時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_NotAuthorized'					: 'カタログサイト情報取得時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_NotFound'							: 'カタログサイト情報取得時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_ValidationError'					: 'カタログサイト情報取得時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_CKANAPIError'						: 'カタログサイト情報取得時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_ServerIncompatibleError'			: 'カタログサイト情報取得時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_AttributeError'					: 'カタログサイト情報取得時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_info_detail_Exception'						: 'カタログサイト情報取得時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'ckaninfo_Exception'									: 'カタログサイト情報取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 組織情報取得エラー
    'get_ckan_user_org_release_NotAuthorized'				: '組織情報取得時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_release_NotFound'					: '組織情報取得時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_release_ValidationError'				: '組織情報取得時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_release_CKANAPIError'				: '組織情報取得時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_release_ServerIncompatibleError'		: '組織情報取得時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_release_AttributeError'				: '組織情報取得時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_release_Exception'					: '組織情報取得時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_NotAuthorized'				: '組織情報取得時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_NotFound'						: '組織情報取得時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_ValidationError'				: '組織情報取得時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_CKANAPIError'					: '組織情報取得時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_ServerIncompatibleError'		: '組織情報取得時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_AttributeError'				: '組織情報取得時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_ckan_user_org_detail_Exception'					: '組織情報取得時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'get_organization_list_Exception'						: '組織情報取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # ラインセンスリスト取得エラー
    'get_license_list_release_NotAuthorized'				: 'ラインセンスリスト取得時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_release_NotFound'						: 'ラインセンスリスト取得時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_release_ValidationError'				: 'ラインセンスリスト取得時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_release_CKANAPIError'					: 'ラインセンスリスト取得時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_release_ServerIncompatibleError'		: 'ラインセンスリスト取得時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_release_AttributeError'				: 'ラインセンスリスト取得時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_release_Exception'					: 'ラインセンスリスト取得時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_NotAuthorized'					: 'ラインセンスリスト取得時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_NotFound'						: 'ラインセンスリスト取得時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_ValidationError'				: 'ラインセンスリスト取得時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_CKANAPIError'					: 'ラインセンスリスト取得時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_ServerIncompatibleError'		: 'ラインセンスリスト取得時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_AttributeError'				: 'ラインセンスリスト取得時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'get_license_list_detail_Exception'						: 'ラインセンスリスト取得時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'licenselist_Exception'									: 'ラインセンスリスト取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログ登録エラー
    'regist_release_catalog_userinfo_NoReleaseCKANInfo'		: '横断検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'regist_release_catalog_NoReleaseCatalogData'			: 'リクエストのデータの中に横断検索カタログデータがありません。',
    'regist_release_catalog_userinfo_NoDetailCKANInfo'		: '詳細検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'regist_release_catalog_NoDetailCatalogData'			: 'リクエストのデータの中に詳細検索カタログデータがありません。',
    'regist_release_release_NotAuthorized'					: '横断検索カタログ登録時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_release_NotFound'						: '横断検索カタログ登録時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_release_ValidationError'				: '横断検索カタログ登録時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_release_CKANAPIError'					: '横断検索カタログ登録時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_release_ServerIncompatibleError'		: '横断検索カタログ登録時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_release_AttributeError'					: '横断検索カタログ登録時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_release_Exception'						: '横断検索カタログ登録時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_NotAuthorized'					: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_NotFound'						: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_ValidationError'					: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_CKANAPIError'					: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_ServerIncompatibleError'			: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_AttributeError'					: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_release_detail_Exception'						: '横断検索カタログ登録での詳細検索カタログ編集時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'regist_release_catalog_Exception'						: '横断検索カタログ登録時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 詳細検索カタログ登録エラー
    'regist_detail_catalog_userinfo_NoDetailCKANInfo'		: '詳細検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'regist_detail_catalog_NoDetailCatalogData'				: 'リクエストのデータの中に詳細検索カタログデータがありません。',
    'regist_detail_catalog_userinfo_NoReleaseCKANInfo'		: '横断検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'regist_detail_catalog_NoReleaseCatalogData'			: 'リクエストのデータの中に横断検索カタログデータがありません。',
    'regist_detail_detail_NotAuthorized'					: '詳細検索カタログ登録時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_detail_NotFound'							: '詳細検索カタログ登録時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_detail_ValidationError'					: '詳細検索カタログ登録時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_detail_CKANAPIError'						: '詳細検索カタログ登録時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_detail_ServerIncompatibleError'			: '詳細検索カタログ登録時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_detail_AttributeError'					: '詳細検索カタログ登録時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_detail_Exception'						: '詳細検索カタログ登録時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_NotAuthorized'					: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_NotFound'						: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_ValidationError'					: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_CKANAPIError'					: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_ServerIncompatibleError'			: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_AttributeError'					: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_detail_release_Exception'						: '詳細検索カタログ登録での横断検索カタログ編集時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'regist_detail_catalog_Exception'						: '詳細検索カタログ登録時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログ・詳細検索カタログ登録エラー
    'regist_both_catalog_userinfo_NoReleaseCKANInfo'		: '横断検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'regist_both_catalog_NoReleaseCatalogData'				: 'リクエストのデータの中に横断検索カタログデータがありません。',
    'regist_both_catalog_userinfo_NoDetailCKANInfo'			: '詳細検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'regist_both_catalog_NoDetailCatalogData'				: 'リクエストのデータの中に詳細検索カタログデータがありません。',
    'regist_both_release_NotAuthorized'						: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_release_NotFound'							: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_release_ValidationError'					: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_release_CKANAPIError'						: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_release_ServerIncompatibleError'			: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_release_AttributeError'					: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_release_Exception'							: '横断検索カタログ・詳細検索カタログ登録時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_NotAuthorized'						: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_NotFound'							: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_ValidationError'					: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_CKANAPIError'						: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_ServerIncompatibleError'			: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_AttributeError'						: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'regist_both_detail_Exception'							: '横断検索カタログ・詳細検索カタログ登録時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'regist_both_catalog_Exception'							: '横断検索カタログ・詳細検索カタログ登録時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログ編集エラー
    'edit_release_catalog_userinfo_NoReleaseCKANInfo'		: '横断検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'edit_release_catalog_NoReleaseCatalogData'				: 'リクエストのデータの中に横断検索カタログデータがありません。',
    'edit_release_NotAuthorized'							: '横断検索カタログ編集時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_release_NotFound'									: '横断検索カタログ編集時に横断検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_release_ValidationError'							: '横断検索カタログ編集時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_release_CKANAPIError'								: '横断検索カタログ編集時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'edit_release_ServerIncompatibleError'					: '横断検索カタログ編集時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_release_AttributeError'							: '横断検索カタログ編集時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_release_Exception'								: '横断検索カタログ編集時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'edit_release_catalog_Exception'						: '横断検索カタログ編集時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 詳細検索カタログ編集エラー
    'edit_detail_catalog_userinfo_NoDetailCKANInfo'			: '詳細検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'edit_detail_catalog_NoDetailCatalogData'				: 'リクエストのデータの中に詳細検索カタログデータがありません。',
    'edit_detail_NotAuthorized'								: '詳細検索カタログ編集時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_detail_NotFound'									: '詳細検索カタログ編集時に詳細検索用CKANで検索エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_detail_ValidationError'							: '詳細検索カタログ編集時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_detail_CKANAPIError'								: '詳細検索カタログ編集時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'edit_detail_ServerIncompatibleError'					: '詳細検索カタログ編集時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_detail_AttributeError'							: '詳細検索カタログ編集時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'edit_detail_Exception'									: '詳細検索カタログ編集時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'edit_detail_catalog_Exception'							: '詳細検索カタログ編集時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログ・詳細検索カタログ編集エラー
    'edit_both_catalog_userinfo_NoReleaseCKANInfo'			: '横断検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'edit_both_catalog_NoReleaseCatalogData'				: 'リクエストのデータの中に横断検索カタログデータがありません。',
    'edit_both_catalog_userinfo_NoDetailCKANInfo'			: '詳細検索用CKANのログイン情報を取得できませんでした。\n管理者に問い合わせてください。',
    'edit_both_catalog_NoDetailCatalogData'					: 'リクエストのデータの中に詳細検索カタログデータがありません。',
    'edit_both_catalog_Exception'							: '横断検索カタログ・詳細検索カタログ編集時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログ検索エラー
    'search_release_catalog_NoUrlOrKeyword'					: 'リクエストのデータの中にURLまたはキーワードがありません。',
    'search_release_release_NotAuthorized'					: '横断検索カタログ検索時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_release_ValidationError'				: '横断検索カタログ検索時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_release_CKANAPIError'					: '横断検索カタログ検索時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_release_ServerIncompatibleError'		: '横断検索カタログ検索時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_release_AttributeError'					: '横断検索カタログ検索時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_release_Exception'						: '横断検索カタログ検索時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'search_release_detail_NotAuthorized'					: '横断検索カタログ検索時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_detail_ValidationError'					: '横断検索カタログ検索時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_detail_CKANAPIError'					: '横断検索カタログ検索時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_detail_ServerIncompatibleError'			: '横断検索カタログ検索時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_detail_AttributeError'					: '横断検索カタログ検索時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_release_detail_Exception'						: '横断検索カタログ検索時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'search_release_catalog_Exception'						: '横断検索カタログ検索時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 詳細検索カタログ検索エラー
    'search_detail_catalog_NoUrlOrKeyword'					: 'リクエストのデータの中にURLまたはキーワードがありません。',
    'search_detail_detail_NotAuthorized'					: '詳細検索カタログ検索時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_detail_ValidationError'					: '詳細検索カタログ検索時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_detail_CKANAPIError'						: '詳細検索カタログ検索時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_detail_ServerIncompatibleError'			: '詳細検索カタログ検索時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_detail_AttributeError'					: '詳細検索カタログ検索時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_detail_Exception'						: '詳細検索カタログ検索時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'search_detail_release_NotAuthorized'					: '詳細検索カタログ検索時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_release_ValidationError'					: '詳細検索カタログ検索時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_release_CKANAPIError'					: '詳細検索カタログ検索時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_release_ServerIncompatibleError'			: '詳細検索カタログ検索時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_release_AttributeError'					: '詳細検索カタログ検索時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_detail_release_Exception'						: '詳細検索カタログ検索時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'search_detail_catalog_Exception'						: '詳細検索カタログ検索時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログ・詳細検索カタログ検索エラー
    'search_catalog_NoUrlOrKeyword'							: 'リクエストのデータの中にURLまたはキーワードがありません。',
    'search_both_release_NotAuthorized'						: '横断検索カタログ・詳細検索カタログ検索時に横断検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_release_ValidationError'					: '横断検索カタログ・詳細検索カタログ検索時に横断検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_release_CKANAPIError'						: '横断検索カタログ・詳細検索カタログ検索時に横断検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_release_ServerIncompatibleError'			: '横断検索カタログ・詳細検索カタログ検索時に横断検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_release_AttributeError'					: '横断検索カタログ・詳細検索カタログ検索時に横断検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_release_Exception'							: '横断検索カタログ・詳細検索カタログ検索時に横断検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'search_both_detail_NotAuthorized'						: '横断検索カタログ・詳細検索カタログ検索時に詳細検索用CKANで認証エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_detail_ValidationError'					: '横断検索カタログ・詳細検索カタログ検索時に詳細検索用CKANで変数エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_detail_CKANAPIError'						: '横断検索カタログ・詳細検索カタログ検索時に詳細検索用CKANでAPIエラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_detail_ServerIncompatibleError'			: '横断検索カタログ・詳細検索カタログ検索時に詳細検索用CKANで互換性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_detail_AttributeError'						: '横断検索カタログ・詳細検索カタログ検索時に詳細検索用CKANで属性エラーが発生しました。\n管理者に問い合わせてください。',
    'search_both_detail_Exception'							: '横断検索カタログ・詳細検索カタログ検索時に詳細検索用CKANで例外が発生しました。\n管理者に問い合わせてください。',
    'search_catalog_Exception'								: '横断検索カタログ・詳細検索カタログ検索時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # カタログ削除エラー
    'delete_catalog_NoRelease'								: 'リクエストのデータの中に横断検索カタログの指定がありません。',
    'delete_catalog_NoDetail'								: 'リクエストのデータの中に詳細検索カタログの指定がありません。',
    'delete_catalog_Exception'								: 'カタログ削除時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログインポートエラー
    'import_release_ckan_NotFound'							: 'インポート対象の横断検索用CKAN情報が不正です。\n管理者に問い合わせてください。',
    'import_release_NoDeleteFlug'							: 'リクエストのデータの中に削除指定がありません。',
    'import_release_NoFile'									: 'インポートファイルが存在しません。',
    'import_release_NoFilename'								: 'インポートファイルが選択されていません。',
    'import_dataset_FileSaveError'							: 'インポートファイルの保存に失敗しました。\n管理者に問い合わせてください。',
    'import_release_Exception'								: '横断検索カタログインポート時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 詳細検索カタログインポートエラー
    'import_detail_ckan_NotFound'							: 'インポート対象の詳細検索用CKAN情報が不正です。\n管理者に問い合わせてください。',
    'import_detail_NoDeleteFlug'							: 'リクエストのデータの中に削除指定がありません。',
    'import_detail_NoFile'									: 'インポートファイルが存在しません。',
    'import_detail_NoFilename'								: 'インポートファイルが選択されていません。',
    'import_detail_Exception'								: '詳細検索カタログインポート時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 横断検索カタログエクスポートエラー
    'export_release_ckan_NotFound'							: 'エクスポート対象の横断検索用CKAN情報が不正です。\n管理者に問い合わせてください。',
    'export_dataset_DirError'								: 'エクスポートフォルダの作成に失敗しました。\n管理者に問い合わせてください。',
    'export_release_Exception'								: '横断検索カタログエクスポート受付時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 詳細検索カタログエクスポートエラー
    'export_detail_ckan_NotFound'							: 'エクスポート対象の詳細検索用CKAN情報が不正です。\n管理者に問い合わせてください。',
    'export_detail_Exception'								: '詳細検索カタログエクスポート受付時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 外部サービスおよび機械学習使用有無確認エラー
    'get_external_service_Exception'						: '外部サービスおよび機械学習使用有無確認時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 地域検索エラー
    'get_geonames_ValueError'								: '検索キーワードが未設定です。',
    'FindByKeyword_name_Timeout'							: '地域検索に失敗しました。\n管理者に問い合わせてください。',
    'FindByKeyword_name_Exception'							: '地域検索に失敗しました。\n管理者に問い合わせてください。',
    'FindByKeyword_name_NotAuthorized'						: '地域検索に失敗しました。\n管理者に問い合わせてください。',
    'FindByKeyword_name_Timeout'							: '地域検索に失敗しました。\n管理者に問い合わせてください。',
    'FindByKeyword_name_HttpError'							: '地域検索に失敗しました。\n管理者に問い合わせてください。',
    'get_geonames_Exception'								: '地域検索時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 地域のフルネーム取得エラー
    'get_fullgeoname_ValueError'							: '地域名IDが未設定です。',
    'getHierarchyList_Timeout'								: '地域のフルネーム取得に失敗しました。\n管理者に問い合わせてください。',
    'getHierarchyList_Exception'							: '地域のフルネーム取得に失敗しました。\n管理者に問い合わせてください。',
    'getHierarchyList_NotAuthorized'						: '地域のフルネーム取得に失敗しました。\n管理者に問い合わせてください。',
    'getHierarchyList_Timeout'								: '地域のフルネーム取得に失敗しました。\n管理者に問い合わせてください。',
    'getHierarchyList_HttpError'							: '地域のフルネーム取得に失敗しました。\n管理者に問い合わせてください。',
    'get_fullgeoname_Exception'								: '地域のフルネーム取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # URL指定ファイル取得エラー
    'http_get_Timeout'										: 'データの取得時にタイムアウトエラーが発生しました。\n管理者に問い合わせてください。',
    'http_get_Exception'									: 'データの取得時にファイル取得エラーが発生しました。\n管理者に問い合わせてください。',
    'http_get_NotAuthorized'								: 'データの取得時に認証エラーが発生しました。\n管理者に問い合わせてください。',
    'http_get_NotFound'										: '取得するファイルが見つかりません。\n管理者に問い合わせてください。',
    'http_get_HttpError'									: 'データの取得時にファイル取得エラーが発生しました。\n管理者に問い合わせてください。',
    'http_get_FileSaveError'								: 'データの取得時にファイル保存エラーが発生しました。\n管理者に問い合わせてください。',
    'ftp_get_Timeout'										: 'データの取得時にタイムアウトエラーが発生しました。\n管理者に問い合わせてください。',
    'ftp_get_NotAuthorized'									: 'データの取得時に認証エラーが発生しました。\n管理者に問い合わせてください。',
    'ftp_get_NotFound'										: '取得するファイルが見つかりません。\n管理者に問い合わせてください。',
    'ftp_get_FTPError'										: 'データの取得時にファイル取得エラーが発生しました。\n管理者に問い合わせてください。',
    'ftp_get_FileSaveError'									: 'データの取得時にファイル保存エラーが発生しました。\n管理者に問い合わせてください。',

    'read_file_JSONFileReadError'							: 'JSONファイル読み込みエラーが発生しました。\n管理者に問い合わせてください。',
    'read_file_CSVFileReadError'							: 'CSVファイル読み込みエラーが発生しました。\n管理者に問い合わせてください。',
    'read_file_ExcelFileReadError'							: 'XLSX,XLSファイル読み込みエラーが発生しました。\n管理者に問い合わせてください。',

    # ファイルアップロードエラー
    'file_upload_NoFile'									: 'ファイルが存在しません。',
    'file_upload_NoFilename'								: 'ファイルが選択されていません。',
    'url_upload_FileSaveError'								: 'ファイルアップロード時にファイル保存エラーが発生しました。\n管理者に問い合わせてください。',
    'get_resource_Exception'								: 'ローカルファイルアップロード時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # NGSIデータ取得エラー
    'get_ngsi_data_NoURL'									: 'NGSIデータのURLが未設定です。',
    'get_ngsi_data_NoTenant'								: 'NGSIテナントが未設定です。',
    'get_ngsi_data_NoServicePath'							: 'NGSIサービスパスが未設定です。',
    'ngsi_ServerException'									: 'NGSIデータ取得時にNGSIサーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'ngsi_RequestError'										: 'NGSIデータのURLが不正です。\n配信の取得先URLを確認してください。',
    'ngsi_TimeoutError'										: 'NGSIデータ取得時にタイムアウトエラーが発生しました。\n管理者に問い合わせてください。',
    'ngsi_ServerError'										: 'NGSIデータ取得時にNGSIサーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'ngsi_FileSaveError'									: 'NGSIデータの保存に失敗しました。\n管理者に問い合わせてください。',
    'ngsi_FileReadError'									: 'NGSIデータの読み込みに失敗しました。\n管理者に問い合わせてください。',
    'ngsi_original_ServerException'							: 'NGSIデータ取得時にNGSIサーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'ngsi_original_RequestError'							: 'NGSIデータのURLが不正です。\n配信の取得先URLを確認してください。',
    'ngsi_original_TimeoutError'							: 'NGSIデータ取得時にタイムアウトエラーが発生しました。\n管理者に問い合わせてください。',
    'ngsi_original_ServerError'								: 'NGSIデータ取得時にNGSIサーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'ngsi_original_FileSaveError'							: 'NGSIデータの保存に失敗しました。\n管理者に問い合わせてください。',
    'get_ngsi_data_Exception'								: 'NGSIデータ取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # NGSIデータモデル取得エラー
    'get_ngsi_data_model_NoURL'								: 'NGSIデータのURLが未設定です。',
    'get_ngsi_data_model_NoTenant'							: 'NGSIテナントが未設定です。',
    'get_ngsi_data_model_NoServicePath'						: 'NGSIサービスパスが未設定です。',
    'get_ngsi_data_model_NoEntityType'						: 'NGSIデータ種別が未設定です。',
    'get_ngsi_data_model_ServerException'					: 'NGSIデータモデル取得時にNGSIサーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ngsi_data_model_RequestError'						: 'NGSIデータのURLが不正です。\n配信の取得先URLを確認してください。',
    'get_ngsi_data_model_TimeoutError'						: 'NGSIデータモデル取得時にタイムアウトエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ngsi_data_model_ServerError'						: 'NGSIデータモデル取得時にNGSIサーバでエラーが発生しました。\n管理者に問い合わせてください。',
    'get_ngsi_data_model_Exception'							: 'NGSIデータモデル取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 前段イベント識別子検索エラー
    'search_history_NoCaddeProviderId'						: '提供者IDが未設定です',
    'search_history_NoAuthCodoe'							: '認可トークンが未設定です。',
    'search_history_Exception'								: '前段イベント識別子検索時に検索エラーが発生しました。\n管理者に問い合わせてください。',

    # 日時分析エラー
    'temporalAnalyzer_NoText'								: '日時分析時にテキストが未設定です。',
    'temporalAnalyzer_NoFilepath'							: '日時分析時にファイルパスが未設定です。',
    'temporalAnalyzer_NoColumnName'							: '日時分析時にカラム名が未設定です。',
    'temporalAnalyzer_NoInputDatetimeFormat'				: '日時分析時に時刻フォーマットが未設定です。',
    'temporalAnalyzer_Exception'							: '日時分析時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 地域分析エラー
    'spatialAnalyzer_NoTitle'								: 'タイトルが未設定です。',
    'spatialAnalyzer_NoFilepath'							: 'ファイルパスが未設定です。',
    'spatialAnalyzer_NoNotes'								: 'ノートが未設定です。',
    'spatialAnalyzer_NoMethod'								: 'メソッドが未設定です。',
    'spatialAnalyzer_FileOpenError'							: '分析対象ファイルの読み込みに失敗しました。\n管理者に問い合わせてください。',
    'spatialAnalyzer_Exception'								: '地域分析時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # テーマ・キーワードの予測分析エラー
    'themeKeywordAnalyzer_NoCatarogTitle'					: 'データセットのタイトルが未設定です。',
    'themeKeywordAnalyzer_NoCatarogDescription'				: 'データセットの説明が未設定です。',
    'themeKeywordAnalyzer_NoAnalyseType'					: '分析種別が未設定です。',
    'themeKeywordAnalyzer_Exception'						: 'テーマ・キーワードの予測分析時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 入力データ一時保存エラー
    'save_temporal_NoTmpFile'								: 'リクエストデータが不正です。\n管理者に問い合わせてください。',
    'save_temporal_NoDataForUpdate'							: 'リクエストデータが不正です。\n管理者に問い合わせてください。',
    'save_temporal_NoDatasetinfo'							: 'リクエストデータが不正です。\n管理者に問い合わせてください。',
    'save_temporal_NoDatajacket'							: 'リクエストデータが不正です。\n管理者に問い合わせてください。',
    'save_temporal_NoDatasetoptionalinfo'					: 'リクエストデータが不正です。\n管理者に問い合わせてください。',
    'save_temporal_NoUserterms'								: 'リクエストデータが不正です。\n管理者に問い合わせてください。',
    'write_tmp_data_FileSaveError'							: '一時保存に失敗しました。\n管理者に問い合わせてください。',
    'save_temporal_Exception'								: '一時保存時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 一時保存データ取得エラー
    'get_tmp_data_files_FileOpenError'						: '一時保存データ取得に失敗しました。\n管理者に問い合わせてください。',
    'get_temporal_Exception'								: '一時保存データ取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # 一時保存データ削除エラー
    'remove_temporal_NoTemporal'							: '削除対象の一時保存データが指定されていません。',
    'remove_temporal_DeleteError'							: '一時保存データ削除に失敗しました。\n管理者に問い合わせてください。',
    'remove_temporal_Exception'								: '一時保存データ削除時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # テンプレート保存エラー
    'save_template_NoTemplateData'							: 'リクエストデータが不正です。テンプレート情報がありません。',
    'get_template_FileSaveError'							: 'テンプレート保存に失敗しました。\n管理者に問い合わせてください。',
    'save_template_Exception'								: 'テンプレート保存時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # テンプレート取得エラー
    'get_template_FileOpenError'							: 'テンプレート取得に失敗しました。\n管理者に問い合わせてください。',
    'get_template_Exception'								: 'テンプレート取得時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # カタログ項目オートコンプリートエラー
    'search_auto_correct_NoLabel'										: 'カタログ項目自動補完候補検索対象フィールドが未設定です。',
    'search_auto_correct_NoValue'										: 'カタログ項目自動補完候補検索検索値が未設定です。',
    'search_auto_correct_catalog_release_NotAuthorized'					: 'カタログ項目自動補完候補検索時に横断検索用CKANで認証エラーが発生しました。',
    'search_auto_correct_catalog_release_NotFound'						: 'カタログ項目自動補完候補検索時に横断検索用CKANで検索エラーが発生しました。',
    'search_auto_correct_catalog_release_ValidationError'				: 'カタログ項目自動補完候補検索時に横断検索用CKANで変数エラーが発生しました。',
    'search_auto_correct_catalog_release_CKANAPIError'					: 'カタログ項目自動補完候補検索時に横断検索用CKANでAPIエラーが発生しました。',
    'search_auto_correct_catalog_release_ServerIncompatibleError'		: 'カタログ項目自動補完候補検索時に横断検索用CKANで互換性エラーが発生しました。',
    'search_auto_correct_catalog_release_AttributeError'				: 'カタログ項目自動補完候補検索時に横断検索用CKANで属性エラーが発生しました。',
    'search_auto_correct_catalog_release_Exception'						: 'カタログ項目自動補完候補検索時に横断検索用CKANで例外が発生しました。',
    'search_auto_correct_catalog_detail_NotAuthorized'					: 'カタログ項目自動補完候補検索時に詳細検索用CKANで認証エラーが発生しました。',
    'search_auto_correct_catalog_detail_NotFound'						: 'カタログ項目自動補完候補検索時に詳細検索用CKANで検索エラーが発生しました。',
    'search_auto_correct_catalog_detail_ValidationError'				: 'カタログ項目自動補完候補検索時に詳細検索用CKANで変数エラーが発生しました。',
    'search_auto_correct_catalog_detail_CKANAPIError'					: 'カタログ項目自動補完候補検索時に詳細検索用CKANでAPIエラーが発生しました。',
    'search_auto_correct_catalog_detail_ServerIncompatibleError'		: 'カタログ項目自動補完候補検索時に詳細検索用CKANで互換性エラーが発生しました。',
    'search_auto_correct_catalog_detail_AttributeError'					: 'カタログ項目自動補完候補検索時に詳細検索用CKANで属性エラーが発生しました。',
    'search_auto_correct_catalog_detail_Exception'						: 'カタログ項目自動補完候補検索時に詳細検索用CKANで例外が発生しました。',
    'search_auto_correct_Exception'										: 'カタログ項目自動補完候補検索時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

    # リソース項目オートコンプリートエラー
    'search_resource_auto_correct_NoLabel'								: 'リソース項目自動補完候補検索対象フィールドが未設定です。',
    'search_resource_auto_correct_NoValue'								: 'リソース項目自動補完候補検索検索値が未設定です。',
    'search_auto_correct_resource_release_NotAuthorized'				: 'リソース項目自動補完候補検索時に横断検索用CKANで認証エラーが発生しました。',
    'search_auto_correct_resource_release_NotFound'						: 'リソース項目自動補完候補検索時に横断検索用CKANで検索エラーが発生しました。',
    'search_auto_correct_resource_release_ValidationError'				: 'リソース項目自動補完候補検索時に横断検索用CKANで変数エラーが発生しました。',
    'search_auto_correct_resource_release_CKANAPIError'					: 'リソース項目自動補完候補検索時に横断検索用CKANでAPIエラーが発生しました。',
    'search_auto_correct_resource_release_ServerIncompatibleError'		: 'リソース項目自動補完候補検索時に横断検索用CKANで互換性エラーが発生しました。',
    'search_auto_correct_resource_release_AttributeError'				: 'リソース項目自動補完候補検索時に横断検索用CKANで属性エラーが発生しました。',
    'search_auto_correct_resource_release_Exception'					: 'リソース項目自動補完候補検索時に横断検索用CKANで例外が発生しました。',
    'search_auto_correct_resource_detail_NotAuthorized'					: 'リソース項目自動補完候補検索時に詳細検索用CKANで認証エラーが発生しました。',
    'search_auto_correct_resource_detail_NotFound'						: 'リソース項目自動補完候補検索時に詳細検索用CKANで検索エラーが発生しました。',
    'search_auto_correct_resource_detail_ValidationError'				: 'リソース項目自動補完候補検索時に詳細検索用CKANで変数エラーが発生しました。',
    'search_auto_correct_resource_detail_CKANAPIError'					: 'リソース項目自動補完候補検索時に詳細検索用CKANでAPIエラーが発生しました。',
    'search_auto_correct_resource_detail_ServerIncompatibleError'		: 'リソース項目自動補完候補検索時に詳細検索用CKANで互換性エラーが発生しました。',
    'search_auto_correct_resource_detail_AttributeError'				: 'リソース項目自動補完候補検索時に詳細検索用CKANで属性エラーが発生しました。',
    'search_auto_correct_resource_detail_Exception'						: 'リソース項目自動補完候補検索時に詳細検索用CKANで例外が発生しました。',
    'search_resource_auto_correct_Exception'							: 'リソース項目自動補完候補検索時にカタログ作成ツールで例外が発生しました。\n管理者に問い合わせてください。',

}


class CatalogToolException(Exception):
    """
    独自Exception
    Exception生成時にメッセージIDを受け取り、エラーメッセージ、httpステータスコードを保持する。
    """
    def __init__(
            self,
            message_id: str,
            status_code: int = None):
        """
        コンストラクタ
        メッセージIDを基に、エラーメッセージ、httpステータスコードを取得し保持する。
        保持している場合は、引数のステータスコードを保持
        Args:
            message_id str : メッセージID
            status_code int : ステータスコード
        """
        self.message_id = message_id
        self.http_status_code = status_code
        self.message = ''
        if message_id in MESSAGE_MAP:
            self.message = MESSAGE_MAP[message_id]
