# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_protocol/ml_analysis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='grpc_protocol/ml_analysis.proto',
    package='mlAnalysis',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1fgrpc_protocol/ml_analysis.proto\x12\nmlAnalysis\"4\n\x08MetaData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"P\n\x14\x41nalysisThemeKeyword\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x61nalyse_type\x18\x03 \x01(\t\"b\n\x10\x41nalysisTemporal\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x03 \x01(\t\x12\x1d\n\x15input_datetime_format\x18\x04 \x01(\t\"M\n\x0f\x41nalysisSpatial\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05notes\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\"S\n\x11ReplyThemeKeyword\x12\x14\n\x0c\x62\x65st_analyse\x18\x01 \x01(\t\x12\x13\n\x0btop_analyse\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\t\"=\n\rReplyTemporal\x12\x16\n\x0estart_datetime\x18\x01 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x02 \x01(\t\"$\n\x0cReplySpatial\x12\x14\n\x0cspatial_list\x18\x01 \x01(\t2\xa1\x02\n\x0e\x41nalyseService\x12\x62\n\x19ThemeKeywordAnalyseServer\x12 .mlAnalysis.AnalysisThemeKeyword\x1a\x1d.mlAnalysis.ReplyThemeKeyword\"\x00(\x01\x30\x01\x12V\n\x15TemporalAnalyseServer\x12\x1c.mlAnalysis.AnalysisTemporal\x1a\x19.mlAnalysis.ReplyTemporal\"\x00(\x01\x30\x01\x12S\n\x14SpatialAnalyseServer\x12\x1b.mlAnalysis.AnalysisSpatial\x1a\x18.mlAnalysis.ReplySpatial\"\x00(\x01\x30\x01\x62\x06proto3'
)


_METADATA = _descriptor.Descriptor(
    name='MetaData',
    full_name='mlAnalysis.MetaData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='mlAnalysis.MetaData.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='type', full_name='mlAnalysis.MetaData.type', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='path', full_name='mlAnalysis.MetaData.path', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=47,
    serialized_end=99,
)


_ANALYSISTHEMEKEYWORD = _descriptor.Descriptor(
    name='AnalysisThemeKeyword',
    full_name='mlAnalysis.AnalysisThemeKeyword',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='title', full_name='mlAnalysis.AnalysisThemeKeyword.title', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='description', full_name='mlAnalysis.AnalysisThemeKeyword.description', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='analyse_type', full_name='mlAnalysis.AnalysisThemeKeyword.analyse_type', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=101,
    serialized_end=181,
)


_ANALYSISTEMPORAL = _descriptor.Descriptor(
    name='AnalysisTemporal',
    full_name='mlAnalysis.AnalysisTemporal',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='text', full_name='mlAnalysis.AnalysisTemporal.text', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='data', full_name='mlAnalysis.AnalysisTemporal.data', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='column_name', full_name='mlAnalysis.AnalysisTemporal.column_name', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='input_datetime_format', full_name='mlAnalysis.AnalysisTemporal.input_datetime_format', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=183,
    serialized_end=281,
)


_ANALYSISSPATIAL = _descriptor.Descriptor(
    name='AnalysisSpatial',
    full_name='mlAnalysis.AnalysisSpatial',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='data', full_name='mlAnalysis.AnalysisSpatial.data', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='title', full_name='mlAnalysis.AnalysisSpatial.title', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='notes', full_name='mlAnalysis.AnalysisSpatial.notes', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='method', full_name='mlAnalysis.AnalysisSpatial.method', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=283,
    serialized_end=360,
)


_REPLYTHEMEKEYWORD = _descriptor.Descriptor(
    name='ReplyThemeKeyword',
    full_name='mlAnalysis.ReplyThemeKeyword',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='best_analyse', full_name='mlAnalysis.ReplyThemeKeyword.best_analyse', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='top_analyse', full_name='mlAnalysis.ReplyThemeKeyword.top_analyse', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='probability', full_name='mlAnalysis.ReplyThemeKeyword.probability', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=362,
    serialized_end=445,
)


_REPLYTEMPORAL = _descriptor.Descriptor(
    name='ReplyTemporal',
    full_name='mlAnalysis.ReplyTemporal',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='start_datetime', full_name='mlAnalysis.ReplyTemporal.start_datetime', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='end_datetime', full_name='mlAnalysis.ReplyTemporal.end_datetime', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=447,
    serialized_end=508,
)


_REPLYSPATIAL = _descriptor.Descriptor(
    name='ReplySpatial',
    full_name='mlAnalysis.ReplySpatial',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='spatial_list', full_name='mlAnalysis.ReplySpatial.spatial_list', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=510,
    serialized_end=546,
)

DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.message_types_by_name['AnalysisThemeKeyword'] = _ANALYSISTHEMEKEYWORD
DESCRIPTOR.message_types_by_name['AnalysisTemporal'] = _ANALYSISTEMPORAL
DESCRIPTOR.message_types_by_name['AnalysisSpatial'] = _ANALYSISSPATIAL
DESCRIPTOR.message_types_by_name['ReplyThemeKeyword'] = _REPLYTHEMEKEYWORD
DESCRIPTOR.message_types_by_name['ReplyTemporal'] = _REPLYTEMPORAL
DESCRIPTOR.message_types_by_name['ReplySpatial'] = _REPLYSPATIAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
    'DESCRIPTOR': _METADATA,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.MetaData)
})
_sym_db.RegisterMessage(MetaData)

AnalysisThemeKeyword = _reflection.GeneratedProtocolMessageType('AnalysisThemeKeyword', (_message.Message,), {
    'DESCRIPTOR': _ANALYSISTHEMEKEYWORD,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.AnalysisThemeKeyword)
})
_sym_db.RegisterMessage(AnalysisThemeKeyword)

AnalysisTemporal = _reflection.GeneratedProtocolMessageType('AnalysisTemporal', (_message.Message,), {
    'DESCRIPTOR': _ANALYSISTEMPORAL,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.AnalysisTemporal)
})
_sym_db.RegisterMessage(AnalysisTemporal)

AnalysisSpatial = _reflection.GeneratedProtocolMessageType('AnalysisSpatial', (_message.Message,), {
    'DESCRIPTOR': _ANALYSISSPATIAL,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.AnalysisSpatial)
})
_sym_db.RegisterMessage(AnalysisSpatial)

ReplyThemeKeyword = _reflection.GeneratedProtocolMessageType('ReplyThemeKeyword', (_message.Message,), {
    'DESCRIPTOR': _REPLYTHEMEKEYWORD,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.ReplyThemeKeyword)
})
_sym_db.RegisterMessage(ReplyThemeKeyword)

ReplyTemporal = _reflection.GeneratedProtocolMessageType('ReplyTemporal', (_message.Message,), {
    'DESCRIPTOR': _REPLYTEMPORAL,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.ReplyTemporal)
})
_sym_db.RegisterMessage(ReplyTemporal)

ReplySpatial = _reflection.GeneratedProtocolMessageType('ReplySpatial', (_message.Message,), {
    'DESCRIPTOR': _REPLYSPATIAL,
    '__module__': 'grpc_protocol.ml_analysis_pb2'
    # @@protoc_insertion_point(class_scope:mlAnalysis.ReplySpatial)
})
_sym_db.RegisterMessage(ReplySpatial)


_ANALYSESERVICE = _descriptor.ServiceDescriptor(
    name='AnalyseService',
    full_name='mlAnalysis.AnalyseService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=549,
    serialized_end=838,
    methods=[
        _descriptor.MethodDescriptor(
            name='ThemeKeywordAnalyseServer',
            full_name='mlAnalysis.AnalyseService.ThemeKeywordAnalyseServer',
            index=0,
            containing_service=None,
            input_type=_ANALYSISTHEMEKEYWORD,
            output_type=_REPLYTHEMEKEYWORD,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='TemporalAnalyseServer',
            full_name='mlAnalysis.AnalyseService.TemporalAnalyseServer',
            index=1,
            containing_service=None,
            input_type=_ANALYSISTEMPORAL,
            output_type=_REPLYTEMPORAL,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='SpatialAnalyseServer',
            full_name='mlAnalysis.AnalyseService.SpatialAnalyseServer',
            index=2,
            containing_service=None,
            input_type=_ANALYSISSPATIAL,
            output_type=_REPLYSPATIAL,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_ANALYSESERVICE)

DESCRIPTOR.services_by_name['AnalyseService'] = _ANALYSESERVICE

# @@protoc_insertion_point(module_scope)
